/* Generated by Nim Compiler v2.3.1 */
#define NIM_INTBITS 64
#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ;
struct tyTuple__RZEZlyko4VRjsGRM9bCskqQ;
struct Exception;
struct tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ {
	NI len;
	NI cap;
	tyTuple__RZEZlyko4VRjsGRM9bCskqQ* d;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg)(Exception* e_p0);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ)(void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw)(Exception* e_p0);
static N_INLINE(void, initStackBottom)(void);
N_LIB_PRIVATE NIM_CONST NI nimStrVersion = ((NI) 2);
N_LIB_PRIVATE NIM_CONST NI nimSeqVersion = ((NI) 2);
N_LIB_PRIVATE TFrame* framePtr__system_u2676;
N_LIB_PRIVATE NI threadId__system_u2941;
N_LIB_PRIVATE tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ roots__system_u3072;
N_LIB_PRIVATE NI rootsThreshold__system_u3282;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__system_u3611;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__system_u3614;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__system_u3616;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook__system_u3619;
static N_INLINE(void, initStackBottom)(void) {
}

N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatslibatssystemdotnim_Init000)(void) {
	{
	initStackBottom();
}
}

